package com.sirelon.marsroverphotos.data.database

import androidx.room.ConstructedBy
import androidx.room.Database
import androidx.room.RoomDatabase
import androidx.room.RoomDatabaseConstructor
import androidx.room.migration.Migration
import androidx.sqlite.SQLiteConnection
import androidx.sqlite.execSQL
import com.sirelon.marsroverphotos.data.database.dao.FactDisplayDao
import com.sirelon.marsroverphotos.data.database.dao.ImagesDao
import com.sirelon.marsroverphotos.data.database.dao.RoverDao
import com.sirelon.marsroverphotos.data.database.entities.FactDisplay
import com.sirelon.marsroverphotos.data.database.entities.MarsImage
import com.sirelon.marsroverphotos.domain.models.Rover

/**
 * Room Database Constructor - generated by KSP for each platform.
 */
expect object AppDataBaseConstructor : RoomDatabaseConstructor<AppDataBase>

/**
 * Created on 2019-03-14 12:54 for Mars-Rover-Photos.
 */
@Database(
    entities = [Rover::class, MarsImage::class, FactDisplay::class],
    version = 9,
    exportSchema = false
)
@ConstructedBy(AppDataBaseConstructor::class)
abstract class AppDataBase : RoomDatabase() {

    abstract fun roversDao(): RoverDao

    abstract fun imagesDao(): ImagesDao

    abstract fun factDisplayDao(): FactDisplayDao

    companion object {
        val migration7To8 = object : Migration(7, 8) {
            override fun migrate(connection: SQLiteConnection) {
                connection.execSQL("ALTER TABLE images ADD COLUMN description TEXT")
                connection.execSQL("ALTER TABLE images ADD COLUMN credit TEXT")
            }
        }

        val migration8To9 = object : Migration(8, 9) {
            override fun migrate(connection: SQLiteConnection) {
                connection.execSQL(
                    "CREATE TABLE IF NOT EXISTS `fact_displays` (`id` INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, `factId` TEXT NOT NULL, `displayTimestamp` INTEGER NOT NULL, `sessionId` TEXT NOT NULL)"
                )
            }
        }
    }
}
